# This file is auto-generated!
# DO NOT EDIT THIS FILE DIRECTLY!
# Instead, edit the Rakefile and run 'rake gems:gemspec'.# -*- encoding: utf-8 -*-

Gem::Specification.new do |gem|
  # See http://docs.rubygems.org/read/chapter/20
  # for more options.
  gem.version           = Lagrange::Version.version
  gem.name              = 'lagrange'
  gem.rubyforge_project = 'lagrange'
  gem.homepage          = 'http://github.com/MrJoy/Lagrange'
  gem.license           = 'MIT'
  gem.summary           = %q{Weaving together all your data.}
  gem.description       = %q{A tool for unifying, syncing, and pushing all sorts of personal data including bookmarks, contacts, etc}
  gem.email             = ['jfrisby@mrjoy.com']
  gem.authors           = ['Jon Frisby']
  gem.require_paths     = ['lib']
  gem.required_ruby_version = '>= 2.1.0'

  # TODO: Exclude irrelevant files.
  # TODO: Exclude test files?
  # TODO: Specify dependencies here instead of in Gemfile.

  includable_files      = `git ls-files -z`.split(/\0/)
  gem.files             = includable_files
  gem.executables       = includable_files.select { |fname| fname.start_with?('bin/') }.map{ |f| f.sub(/^bin\//, '') }
  gem.extra_rdoc_files  = includable_files.select { |fname| fname.end_with?('.md') }
end
