# This file is auto-generated!
# DO NOT EDIT THIS FILE DIRECTLY!
# Instead, edit the Rakefile and run 'rake gems:gemspec'.# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "lagrange"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jon Frisby"]
  s.date = "2013-01-01"
  s.description = "A tool for unifying, syncing, and pushing all sorts of personal data including bookmarks, contacts, etc"
  s.email = ["jfrisby@mrjoy.com"]
  s.executables = ["mirrord/import.rb", "misc_urls/pull.rb", "safari/import.rb", "safari/pull.rb"]
  s.extra_rdoc_files = ["CHANGELOG.md", "NOTES.md", "README.md", "TODO.md"]
  s.files = ["CHANGELOG.md", "NOTES.md", "README.md", "TODO.md", "bin/mirrord/import.rb", "bin/misc_urls/pull.rb", "bin/safari/import.rb", "bin/safari/pull.rb", "lagrange.gemspec", "lib/lagrange.rb", "lib/lagrange/cli.rb", "lib/lagrange/data_types/urls.rb", "lib/lagrange/git.rb", "lib/lagrange/model.rb", "lib/lagrange/modules/firefox/schema.sql", "lib/lagrange/modules/mirrord.rb", "lib/lagrange/modules/misc_urls.rb", "lib/lagrange/modules/safari.rb", "lib/lagrange/monkeypatches.rb", "lib/lagrange/version.rb"]
  s.homepage = "http://github.com/MrJoy/Lagrange"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9.3")
  s.rubyforge_project = "lagrange"
  s.rubygems_version = "1.8.24"
  s.summary = "Weaving together all your data."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<clint>, [">= 0"])
      s.add_runtime_dependency(%q<grit>, [">= 0"])
      s.add_runtime_dependency(%q<virtus>, [">= 0"])
      s.add_runtime_dependency(%q<addressable>, [">= 0"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<plist>, [">= 0"])
      s.add_runtime_dependency(%q<contacts>, [">= 0"])
      s.add_runtime_dependency(%q<mirrored>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<clint>, [">= 0"])
      s.add_dependency(%q<grit>, [">= 0"])
      s.add_dependency(%q<virtus>, [">= 0"])
      s.add_dependency(%q<addressable>, [">= 0"])
      s.add_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_dependency(%q<plist>, [">= 0"])
      s.add_dependency(%q<contacts>, [">= 0"])
      s.add_dependency(%q<mirrored>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<clint>, [">= 0"])
    s.add_dependency(%q<grit>, [">= 0"])
    s.add_dependency(%q<virtus>, [">= 0"])
    s.add_dependency(%q<addressable>, [">= 0"])
    s.add_dependency(%q<yajl-ruby>, [">= 0"])
    s.add_dependency(%q<plist>, [">= 0"])
    s.add_dependency(%q<contacts>, [">= 0"])
    s.add_dependency(%q<mirrored>, [">= 0"])
  end
end
