PROJECT_NAME='lagrange'
GEMSPEC="#{PROJECT_NAME}.gemspec"

task :sanity_check do
  # TODO: Switch to Rugged...
  pending_changes = `git status --porcelain --untracked-files=no`.strip.split("\n").count
  if(pending_changes > 0)
    raise "Refusing to build gem -- your working copy is dirty!  Please commit changes to ensure your gem doesn't include stuff that may get lost!"
  end
end
task :gem => :sanity_check

# TODO: Ditch mg...
require 'mg'
begin
  MG.new(GEMSPEC)
rescue Exception => e
  STDERR.puts("WARNING: Couldn't read gemspec.  As such, a number of tasks may be unavailable to you until you run 'rake gemspec' to correct the issue.")
  STDERR.puts(e.inspect)
  # Gemspec is probably in a broken state, so let's give ourselves a chance to
  # build a new one...
end

DEVELOPMENT_GROUPS=[:development, :test]
RUNTIME_GROUPS=Bundler.definition.groups - DEVELOPMENT_GROUPS
desc "(Re-)build the gemspec based on what's currently committed to git."
task :gemspec do
  indexed_files=Set.new(`git ls-files -- .`.split("\n"))
  ignored_files=Set.new(`git ls-files --exclude-standard --exclude-from=.gitignore-gem --ignored -- .`.split("\n"))
  includable_files=(indexed_files - ignored_files).to_a.sort

  spec = Gem::Specification.new do |gem|
    # See http://docs.rubygems.org/read/chapter/20
    # for more options.
    gem.version           = Lagrange::Version.version
    gem.name              = PROJECT_NAME
    gem.rubyforge_project = PROJECT_NAME
    gem.homepage          = 'http://github.com/MrJoy/Lagrange'
    gem.license           = 'MIT'
    gem.summary           = %q{Weaving together all your data.}
    gem.description       = %q{A tool for unifying, syncing, and pushing all sorts of personal data including bookmarks, contacts, etc}
    gem.email             = ['jfrisby@mrjoy.com']
    gem.authors           = ['Jon Frisby']
    gem.require_paths     = ['lib']
    gem.required_ruby_version = '>= 1.9.3'

    Bundler.load.dependencies_for(*RUNTIME_GROUPS).each do |dep|
      runtime_resolved = Bundler.definition.specs_for(RUNTIME_GROUPS).select { |spc| spc.name == dep.name }.first
      if(!runtime_resolved.nil?)
        gem.add_dependency(dep.name, dep.requirement)
      end
    end

    gem.executables = includable_files.select { |fname| fname.start_with?('bin/') }.map{ |f| f.sub(/^bin\//, '') }
    gem.extra_rdoc_files = includable_files.select { |fname| fname.end_with?('.md') }
    gem.files = includable_files
  end
  File.open(GEMSPEC, 'wb') do |fh|
    fh.write("# This file is auto-generated!\n")
    fh.write("# DO NOT EDIT THIS FILE DIRECTLY!\n")
    fh.write("# Instead, edit the Rakefile and run 'rake gems:gemspec'.")
    fh.write(spec.to_ruby)
  end
end

task :gem => [:gemspec] # Always ensure gemspec is up-to-date when building...
